name: tests

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout GitHub workspace
        uses: actions/checkout@v2

      - name: Install python and chromedriver, activate venv, install dependencies, & run tests
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv
          ./chromedriverinstall.sh
          ./setup.sh
          ./runtests.sh
